version: 2
updates:
  - package-ecosystem: maven
    directory: "/cnf"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    target-branch: develop
    groups:
      influxdb:
        patterns:
          - "com.influxdb:*"
      fastexcel:
        patterns:
          - "org.dhatim:fastexcel"
          - "org.dhatim:fastexcel-reader"

  - package-ecosystem: npm
    directory: "/ui"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    target-branch: develop
    groups:
      angular:
        patterns:
          - "@angular/*"
          - "@angular-devkit/*"
          - "@angular-eslint/*"
      capacitor:
        patterns:
          - "@capacitor/*"
      ionic-native:
        patterns:
          - "@ionic-native/*"
      ngx-formly:
        patterns:
          - "@ngx-formly/*"
      karma:
        patterns:
          - "karma-*"
          - "karma"
      eslint:
        patterns:
          - "@stylistic/eslint-plugin"
          - "@typescript-eslint/*"
          - "eslint-*"
          - "eslint"

  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    target-branch: develop
