sudo: false

matrix:
  include:
    - language: java
      jdk:
       - openjdk8
      script:
       - ./gradlew build -x test
       - ./gradlew buildAggregatedJavadocs --continue
       - ./gradlew buildAntoraDocs --continue
      deploy:
        provider: pages
        skip-cleanup: true
        github-token: $GITHUB_TOKEN
        keep-history: true
        on:
          branch: develop
        repo: OpenEMS/openems.io
        target-branch: master
        local-dir: build/www

    - language: node_js
      node_js:
       - 10
      script:
       - ./gradlew buildUiForEdge --continue

notifications:
    webhooks: https://www.travisbuddy.com/