name: Enforce Branch Name Semantics
on:
  pull_request:
    branches: ["veloce"]
  workflow_dispatch:
jobs:
  lint-branch-name:
    name: Lint Branch Name
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/github-script@v6
        with:
          result-encoding: string
          script: |
            const enforceGitFlow = (branchName) => {
              const gitFlowFormat = /(feat\W|feature\/|fix\/|chore\/|refactor\/|dependabot\/)/
              if (!gitFlowFormat.test(currentBranch)) {
                core.setFailed(
                  `Branch names in PRs should use Gitflow. e.g. (feat, fix, chore, refactor).  To fix. ` +
                  `perform: git branch -m <new_branch_name> && git push origin -u <:<old_branch_name> <new_branch_name>`)
              }
            }
            const currentBranch = context.payload.pull_request.head.ref
            enforceGitFlow(currentBranch)
