name: Build OpenEMS
on: [push]
jobs:
  build-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Java 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Setup Cache for Java/Gradle
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle-

      - name: Setup Cache for Java/Maven
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Setup Cache for Node.js
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-

      - name: Build all Java packages
        run: ./gradlew build

      - name: Resolve OpenEMS Backend bundles
        run: ./gradlew resolve.BackendApp

      - name: Validate BackendApp.bndrun
        run: git diff --exit-code io.openems.backend.application/BackendApp.bndrun

      - name: Resolve OpenEMS Edge bundles
        run: ./gradlew resolve.EdgeApp

      - name: Validate EdgeApp.bndrun
        run: git diff --exit-code io.openems.edge.application/EdgeApp.bndrun

      - name: Build OpenEMS UI
        run: |
          cd ui
          npm ci --prefer-offline --cache ~/.npm
          node_modules/@angular/cli/bin/ng build -c "openems,openems-edge-prod,prod"

      #
      # Is this a Tag? Prepare release assets and create a draft release
      #
      - name: Prepare Edge+Backend assets
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          ./gradlew buildEdge buildBackend

      - name: Prepare UI asset
        if: startsWith(github.ref, 'refs/tags/')
        uses: edgarrc/action-7z@v1
        with:
          args: 7z a openems-ui.zip ./ui/target/*

      - name: Create draft Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: |
            build/openems-edge.jar
            build/openems-backend.jar
            openems-ui.zip