name: Build OpenEMS UI
on: [push]
jobs:
  build-edge-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14'

      - name: Build OpenEMS UI
        run: ./gradlew buildUiForEdge --continue