name: Build OpenEMS Docker Image

on:
  push:
    branches:
      - main
      - 'workflow/**'
    tags:
      - "*.*.*"

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: [edge, backend, edge-ui, backend-ui]
        include:
          - image: edge
            dockerfile: tools/docker/edge/openems/Dockerfile
            repo: openems/edge
          - image: edge-ui
            dockerfile: tools/docker/edge/ui/Dockerfile
            repo: openems/edge-ui
          - image: backend
            dockerfile: tools/docker/backend/openems/Dockerfile
            repo: openems/backend
          - image: backend-ui
            dockerfile: tools/docker/backend/ui/Dockerfile
            repo: openems/backend-ui

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Reenable later
      #- name: Login to DockerHub
      #  uses: docker/login-action@v2
      #  with:
      #    username: ${{ secrets.DOCKERHUB_USERNAME }}
      #    password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ matrix.repo }}
            ghcr.io/${{ matrix.repo }}
          tags: |
            type=ref,event=tag
          labels: |
            org.opencontainers.image.authors=OpenEMS.io
            org.opencontainers.image.title=OpenEMS ${{ matrix.image }}
            org.opencontainers.image.vendor=OpenEMS.io

      - name: Build and push Docker images
        uses: docker/build-push-action@v4.2.1
        with:
          file: ${{ matrix.dockerfile }}
          platforms: linux/amd64, linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}